ffmpeg -i audiosets/continentes/agnus-dei.wav audiosets/continentes/agnus-dei.ogg
ffmpeg -i audiosets/continentes/are-are.wav audiosets/continentes/are-are.ogg
ffmpeg -i audiosets/continentes/ballade.wav audiosets/continentes/ballade.ogg
ffmpeg -i audiosets/continentes/camino.wav audiosets/continentes/camino.ogg
ffmpeg -i audiosets/continentes/ed-lewis.wav audiosets/continentes/ed-lewis.ogg
ffmpeg -i audiosets/continentes/funeraire.wav audiosets/continentes/funeraire.ogg
ffmpeg -i audiosets/continentes/indvumo.wav audiosets/continentes/indvumo.ogg
ffmpeg -i audiosets/continentes/madinda.wav audiosets/continentes/madinda.ogg
ffmpeg -i audiosets/continentes/mariola.wav audiosets/continentes/mariola.ogg
ffmpeg -i audiosets/continentes/mississipi.wav audiosets/continentes/mississipi.ogg
ffmpeg -i audiosets/continentes/mocita.wav audiosets/continentes/mocita.ogg
ffmpeg -i audiosets/continentes/nubian.wav audiosets/continentes/nubian.ogg
ffmpeg -i audiosets/continentes/ogbeler.wav audiosets/continentes/ogbeler.ogg
ffmpeg -i audiosets/continentes/orillas.wav audiosets/continentes/orillas.ogg
ffmpeg -i audiosets/continentes/ossie.wav audiosets/continentes/ossie.ogg
ffmpeg -i audiosets/continentes/pae.wav audiosets/continentes/pae.ogg
ffmpeg -i audiosets/continentes/rueda.wav audiosets/continentes/rueda.ogg
ffmpeg -i audiosets/continentes/tabla.wav audiosets/continentes/tabla.ogg
